server:
  port: 8001

mybatis:
  type-aliases-package: com.zeng.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.183.128:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=PRC
    username: root
    password: 123456

#eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      # 注册中心地址7001-7003
#      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001   #修改Eureka上的默认描述信息

#info配置
info:
 app.name: zengjiabinstudy
 company.name: zengjiabincompany
